dist: xenial
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "pypy"
  - "pypy3.5"

install:
  - |
    if [[ $TRAVIS_PYTHON_VERSION == pypy3 || $TRAVIS_PYTHON_VERSION == 3.* ]]; then
      pip install -r requirements-py3-devel.txt
    else
      pip install -r requirements-py2-devel.txt
    fi
  - pip install pytest-cov coveralls

before_script:
  - |
    if [[ $TRAVIS_PYTHON_VERSION == pypy || $TRAVIS_PYTHON_VERSION == pypy3 ]]; then
      export PYEXECS=$TRAVIS_PYTHON_VERSION
    else
      export PYEXECS=python$TRAVIS_PYTHON_VERSION
    fi

script:
  - ./tests/run_tests.sh --pytest-cov

after_success: coveralls
